site_url: https://devspills.com
site_name: Dev's Pills
site_description: Dev's Pills Blog
site_author: Rafał Schmidt
copyright: Rafał Schmidt
# repo_url: https://github.com/rafalschmidt97/devspills-blog
# edit_uri: edit/main/blog/
# repo_name: 'devspills-blog'

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rafalschmidt/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rafalschmidt97
  generator: false

docs_dir: src

theme:
  name: material
  favicon: assets/favicon-32x32.png
  custom_dir: src/theme
  static_templates:
    - home.html
  language: pl
  # locale: pl

extra_css:
  - assets/variables.css
  - assets/main-overrides.css
  - assets/page.css
  - assets/home.css
  - assets/custom-blog.css
  - assets/cookies.css

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink

nav:
  - "Wpisy": "index.md"
  - "Tagi": "tagi.md"
  - "O mnie": "o-mnie.md"

plugins:
  - tags:
      tags_file: tagi.md
  - social:
      cards: false
  # - search
  # - exclude-search:
  #     exclude:
  - blogging:
      dirs:
        - .
      paging: false
      sort:
        from: new
        by: creation
      locale: pl-PL
      template: src/theme/custom-blog.html
      # time is used to change the display style of the time, with higher priority than locale.
      time_format: "%d.%m.%Y"
      #meta is used to tell the plugin how to parse the given time string from the meta. 
      # When meta_time_format is set, for all posts with a time or date metadata, the plugin 
      # will use this format to parse the that time, and replace the time from git logs
      meta_time_format: "%d.%m.%Y"

  - git-revision-date-localized:
      custom_format: "%d.%m.%Y"
      type: custom
      locale: pl
      enable_creation_date: true
      fallback_to_build_date: true
      exclude:
        - index.md
        - tagi.md
        - o-mnie.md
  - minify:
      minify_html: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
          remove_optional_attribute_quotes: false
      cache_safe: true
      css_files:
          - assets/variables.css
          - assets/main-overrides.css
          - assets/page.css
          - assets/home.css
          - assets/custom-blog.css
          - assets/cookies.css