site_url: https://devspills.com
site_name: Dev's Pills
site_description: Dev's Pills Blog
site_author: Rafał Schmidt
copyright: 'Rafał Schmidt'

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/rafalschmidt/
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/rafalschmidt97
  generator: false

# repo_url: https://github.com/rafalschmidt97/devspills-blog
# edit_uri: edit/main/blog/
# repo_name: 'devspills-blog'

docs_dir: blog

theme:
  name: material
  custom_dir: blog/theme
  static_templates:
      - home.html
  language: pl

extra_css:
  - theme/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink

nav:
  - 'Wpisy': 'index.md'
  - 'Tagi': 'tagi.md'
  - 'O mnie': 'o-mnie.md'

plugins:
  - tags:
      tags_file: tagi.md
  - social:
      cards: false
  # - search
  # - exclude-search:
  #     exclude:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      exclude:
        - index.md
        - tagi.md
        - o-mnie.md