site_url: http://localhost
site_name: Dev's pills blog
site_description: Dev's pills blog
site_author: Rafał Schmidt
copyright: 'Rafał Schmidt'

repo_url: https://github.com/rafalschmidt97/devspills-blog
repo_name: 'devspills-blog'
edit_uri: edit/main/blog/
docs_dir: blog

theme:
  name: material
  features:
    - navigation.sections

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink

plugins:
  - search
  - git-revision-date-localized
  - blogging:
    dirs:
      - blog