# Sample workflow for building and deploying a MkDocs site to GitHub Pages
name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build site
        run: mkdocs build --config-file ./mkdocs.yml --site-dir ./_site

      - name: Install reprec
        run: pip install reprec

      - name: Run custom replacement script
        run: ./scripts/replace-relative-paths-build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages

